var BoidTypes = {
    Pink: {
        id: 1,
        color: 'pink',
        size: 8,
        baseAcceleration: 25,
        maxAcceleration: 30,
        directRadius: 250,
        repelRadius: 150,
        attractRadius: 200,
        proximityAngle: 2 * Math.PI / 3,
    },
    Red: {
        id: 2,
        color: 'red',
        size: 8,
        baseAcceleration: 15,
        maxAcceleration: 20,
        directRadius: 100,
        repelRadius: 60,
        attractRadius: 150,
        proximityAngle: 2 * Math.PI / 3,
    },
    Cyan: {
        id: 3,
        color: 'cyan',
        size: 8,
        baseAcceleration: 18,
        maxAcceleration: 22,
        directRadius: 75,
        repelRadius: 50,
        attractRadius: 150,
        proximityAngle: 2 * Math.PI / 3,
    }
}