var BoidTypes = {
    Pink: {
        id: 1,
        color: 'pink',
        size: 8,
        baseAcceleration: 15,
        maxAcceleration: 20,
        proximityRadius: 150,
        directRadius: 120,
        repelRadius: 150,
        attractRadius: 120,
        proximityAngle: 2 * Math.PI / 3,
    },
    Red: {
        id: 2,
        color: 'red',
        size: 8,
        baseAcceleration: 15,
        maxAcceleration: 20,
        proximityRadius: 150,
        directRadius: 100,
        repelRadius: 60,
        attractRadius: 150,
        proximityAngle: 2 * Math.PI / 3,
    },
    Cyan: {
        id: 3,
        color: 'cyan',
        size: 8,
        baseAcceleration: 15,
        maxAcceleration: 20,
        proximityRadius: 150,
        directRadius: 150,
        repelRadius: 150,
        attractRadius: 150,
        proximityAngle: 2 * Math.PI / 3,
    }
}